# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-bear-detection',
                'doc_host': 'https://itaysegev.github.io',
                'git_url': 'https://github.com/itaysegev/nbdev-bear-detection',
                'lib_path': 'nbdev_bear_detection'},
  'syms': {'nbdev_bear_detection.core': {'nbdev_bear_detection.core.foo': ('core.html#foo', 'nbdev_bear_detection/core.py')}}}
